### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by MeatDuck** [yadomi/docker-repetier-server#4]
installed on rasbian
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by yadomi** [comment]
Hello, can you describe a little bit more how you ended up with this error ? thank you

**Comment by Rindula** [comment]
Hello,

after looking around for similar problems I found this: https://github.com/docker-library/mysql/issues/228

According to this, you have a 32-Bit-like Architechture, which is not supported by either Docker or the Image. So you either have to change your raspbian Image, or use Google to solve your Problem, since I would have to do the same.

Greetings
Rindula

**Comment by MeatDuck** [comment]
my issue because of using debian-amd64/Repetier-Server-0.93.1-Linux.deb repetier-server.deb on rasbian, they are incompatible

**Comment by Jan-T-Berg** [comment]
Same Issue here.

Raspberry Pi OS with Docker 

docker run -it -p 3344:3344 -v repetier-data:/data --device=/dev/ttyUSB0 --name repetier-server yadomi/repetier-server
exec /usr/local/Repetier-Server/bin/RepetierServer: exec format error
